apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: redis-pv
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
