apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: talk-space-redis
spec:
  type: ClusterIP
  selector:
    app: talk-space-redis
  ports:
    - port: 6379
      targetPort: 6379
