"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from decouple import config
import logging.config
from datetime import timedelta
from kombu import Queue
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = ["*"]

ENVIRONMENT = config("ENVIRONMENT", default="STAGE")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "accounts",
    "blacklist",
    "inbox",
    "externals",
    "django_celery_beat",
]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "blacklist.middleware.BlacklistMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=6),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "AUTH_HEADER_TYPES": ("Token",),
}

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("TALK_SPACE_DB_ENGINE", default="django.db.backends.postgresql"),
        "NAME": config("TALK_SPACE_DB_NAME", default="postgres"),
        "USER": config("TALK_SPACE_DB_USER", default="talk-space"),
        "PASSWORD": config("TALK_SPACE_DB_PASSWORD", default="talk1234"),
        "HOST": config("TALK_SPACE_DB_HOST", default="db"),
        "PORT": config("TALK_SPACE_DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


GLOBAL_REDIS_HOST = config("GLOBAL_REDIS_HOST", default="localhost")
GLOBAL_REDIS_PORT = config("GLOBAL_REDIS_PORT", default="6379")
GLOBAL_REDIS_PASSWORD = config("GLOBAL_REDIS_PASSWORD", default=None)
GLOBAL_REDIS_DB = config("GLOBAL_REDIS_DB", default="0")
REDIS_HOST_URL = config("REDIS_HOST_URL", default=f"redis://127.0.0.1:6379/")


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_DIR = os.path.join(BASE_DIR, "asset")
STATICFILES_DIRS = [
    STATIC_DIR,
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # Disable access for all origins for security
CORS_ALLOW_PRIVATE_NETWORK = True  # Allow requests from private network addresses
CORS_ALLOW_CREDENTIALS = True  # Allow credentials like cookies or Authorization headers

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING_CONFIG = None

BASE_LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "console": {
            "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "formatter": "console",
            "stream": sys.stdout,
        },
    },
    "loggers": {
        "django.request": {
            "level": "DEBUG",
            "propagate": False,
            "handlers": [
                "stdout",
            ],
        },
        "webhook": {
            "level": "INFO",
            "handlers": [
                "stdout",
            ],
            "propagate": False,
        },
        "stdout": {
            "level": "INFO",
            "propagate": False,
            "handlers": [
                "stdout",
            ],
        },
    },
}

logging.config.dictConfig(BASE_LOGGING_CONFIG)


USE_CELERY = config("USE_CELERY", cast=int, default=1)
USE_BEAT = config("USE_BEAT", cast=int, default=1)

if USE_CELERY:
    CELERY_BROKER_URL = REDIS_HOST_URL + "1"
    CELERY_RESULT_BACKEND = REDIS_HOST_URL + "2"
    CELERY_ACCEPT_CONTENT = ["application/json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_ENABLE_UTC = True
    CELERY_TIMEZONE = "UTC"

    CELERY_TASK_DEFAULT_QUEUE = "default"
    CELERY_TASK_DEFAULT_EXCHANGE = "tasks"
    CELERY_TASK_DEFAULT_EXCHANGE_TYPE = "topic"
    CELERY_TASK_DEFAULT_ROUTING_KEY = "default"
    CELERY_TASK_TRACK_STARTED = True
    CELERY_ACKS_LATE = True
    CELERY_BROKER_TRANSPORT = "redis"
    BROKER_CONNECTION_RETRY = True
    BROKER_CONNECTION_RETRY_ON_STARTUP = True
    BROKER_HEARTBEAT = 60
    BROKER_CONNECTION_TIMEOUT = 30
    BROKER_TRANSPORT_OPTIONS = {
        "socket_keepalive": True,
        "health_check_interval": 2,
        "heartbeat_interval": 30,
        "max_retries": 3,
    }

    CELERY_TASK_QUEUES = (
        Queue("default", routing_key="default"),
        Queue("heartbeat", routing_key="heartbeat"),
    )

if USE_BEAT:
    CELERY_BEAT_SCHEDULE = {
        "task_trigger_health_check": {
            "task": "accounts.tasks.task_trigger_health_check",
            "schedule": crontab(minute="*/2"),
            "options": {"queue": "heartbeat", "routing_key": "heartbeat"},
        },
    }
