version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=talk-space
      - POSTGRES_PASSWORD=talk1234
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
