FROM python:3.11-slim-bookworm as prod

ENV POETRY_HOME="/opt/poetry" \
    PATH="/opt/poetry/bin:$PATH" \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y\
    gcc curl\
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry==1.8.5

COPY ./pyproject.toml ./poetry.lock /app/

WORKDIR /app

RUN poetry install

RUN apt-get purge -y \
  gcc \
  && rm -rf /var/lib/apt/lists/*

COPY ./. /app

RUN chmod +x /app/entrypoint.sh

# TODO: Remove the below line when using docker compose or kubernetes

ENTRYPOINT [ "/app/entrypoint.sh" ]
