version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
      - redis
      - redis-listener

  db:
    image: postgres:15.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=talk-space
      - POSTGRES_PASSWORD=talk1234
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: bitnami/redis:6.2.5
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: "SFndjwndk@32424@$#$332"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 30s
      retries: 50

  redis-listener:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    command: python ./src/manage.py start_redis_inbox_listener

    volumes:
      - redis_data:/var/lib/redis/data/

volumes:
  postgres_data:
  redis_data:
