apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-celery-default
  labels:
    app: celery-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-default
  template:
    metadata:
      labels:
        app: celery-default
    spec:
      containers:
        - name: celery-default
          image: IMAGE_PLACEHOLDER
          env:
          - name: USE_CELERY
            value: "1"
          - name: CELERY_BROKER_URL
            value: "redis://:8765@redis:6379/1"
          - name: CELERY_RESULT_BACKEND
            value: "redis://:8765@redis:6379/1"
          - name: PYTHONPATH
            value: "/app/src"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.3"
              memory: "128Mi"
            requests:
              cpu: "0.3"
              memory: "128Mi"
          command:
            - "bash"
            - "-c"
            - "celery -A core worker --loglevel=INFO -Q default --hostname=basic@%h --logfile=/code/logs/celery.log"
