apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: talk-space-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talk-space-app
  template:
    metadata:
      labels:
        app: talk-space-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done']
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done']
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          command: ["./entrypoint.sh"]
