# Generated by Django 5.2 on 2025-05-17 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=255)),
                ("is_group", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="", max_length=255)),
                ("last_message_timestamp", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "inbox",
            },
        ),
        migrations.CreateModel(
            name="InboxMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(choices=[("admin", "admin"), ("user", "user")], default="user", max_length=255),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("inbox", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inbox.inbox")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "inbox_member",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(default="")),
                ("has_attachment", models.BooleanField(default=False)),
                ("is_queued", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_delivered", models.BooleanField(default=False)),
                ("is_seen", models.BooleanField(default=False)),
                ("is_failed", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inbox", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inbox.inbox")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "message",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("file_url", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inbox.message")),
            ],
            options={
                "db_table": "attachment",
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reaction", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inbox.message")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "message_reaction",
            },
        ),
    ]
