# Generated by Django 5.2 on 2025-05-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_delivered",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_failed",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_queued",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_seen",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_sent",
        ),
        migrations.AddField(
            model_name="inbox",
            name="last_message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="inboxmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inboxmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_queued", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_delivered", models.BooleanField(default=False)),
                ("is_seen", models.BooleanField(default=False)),
                ("is_failed", models.BooleanField(default=False)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inbox.message")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
