# Generated by Django 5.2 on 2025-05-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_remove_message_is_delivered_remove_message_is_failed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inbox",
            old_name="last_message_timestamp",
            new_name="last_message_timestamp_old",
        ),
    ]
