# Generated by Django 5.2 on 2025-05-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0003_rename_last_message_timestamp_inbox_last_message_timestamp_old"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="last_message_timestamp_old",
        ),
    ]
