# Generated by Django 5.2 on 2025-05-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0005_inbox_last_message_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="created_by",
        ),
        migrations.AlterModelTable(
            name="messagestatus",
            table="message_status",
        ),
    ]
