# Generated by Django 5.2 on 2025-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0006_remove_inbox_created_by_alter_messagestatus_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="created_by",
            field=models.IntegerField(default=None),
        ),
    ]
