# Generated by Django 5.2 on 2025-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0007_inbox_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbox",
            name="created_by",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
