# Generated by Django 5.2 on 2025-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0008_alter_inbox_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="last_message_sender",
            field=models.IntegerField(default=0),
        ),
    ]
