# Generated by Django 5.2 on 2025-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0009_inbox_last_message_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inbox",
            old_name="group_name",
            new_name="inbox_name",
        ),
        migrations.AddField(
            model_name="inbox",
            name="profile_photo",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
