# Generated by Django 5.2 on 2025-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0010_rename_group_name_inbox_inbox_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="inbox",
            name="is_muted",
        ),
        migrations.AddField(
            model_name="inboxmember",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inboxmember",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
    ]
