# Generated by Django 5.2 on 2025-06-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0011_remove_inbox_is_archived_remove_inbox_is_muted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmember",
            name="nickname",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
