# Generated by Django 5.2 on 2025-04-23 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("profile_photo", models.CharField(default=None, max_length=255, null=True)),
                ("phone_number", models.CharField(default=None, max_length=255, null=True)),
                ("city", models.CharField(default=None, max_length=255, null=True)),
                ("country", models.CharField(default=None, max_length=255, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("user", "user"),
                            ("moderator", "moderator"),
                            ("superuser", "superuser"),
                            ("guest", "guest"),
                            ("manager", "manager"),
                        ],
                        default="guest",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("suspended", "suspended"),
                            ("deleted", "deleted"),
                            ("deactivated", "deactivated"),
                        ],
                        default="inactive",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_info",
            },
        ),
    ]
